development:
  adapter: postgresql
  encoding: unicode
  database: Blocipedia_development
  pool: 5
  username: yunhong
  password:
    timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: Blocipedia_test
  pool: 5
  username: yunhong
  password:
    timeout: 5000
